### ISSUE TITLE
HA 2022.7.x and Python 3.10 creates issue on crow_base_client.py

### ISSUE THREAD

**Issue by acdcnow** [febalci/ha_pycrowipmodule#3]
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: July 9, 2022 at 16:01:01 (1 occurrences)
Last logged: July 9, 2022 at 16:01:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pycrowipmodule/crow_base_client.py", line 195, in keep_alive
    await asyncio.sleep(self._alarmPanel.keepalive_interval, loop=self._eventLoop)
TypeError: sleep() got an unexpected keyword argument 'loop'

**Comment by acdcnow** [comment]
2022-07-11 21:05:15 INFO (MainThread) [custom_components.crowipmodule] Start CrowIpModule.
2022-07-11 21:05:15 INFO (MainThread) [pycrowipmodule.crow_base_client] Latching onto existing event loop...
2022-07-11 21:05:15 INFO (MainThread) [pycrowipmodule.crow_base_client] Starting connection to Crow IP Module... at 1xx.xxx.xxx.xxx:5002
2022-07-11 21:05:15 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/pycrowipmodule/crow_base_client.py", line 195, in keep_alive
await asyncio.sleep(self._alarmPanel.keepalive_interval, loop=self._eventLoop)
TypeError: sleep() got an unexpected keyword argument 'loop'
2022-07-11 21:05:16 INFO (MainThread) [pycrowipmodule.crow_base_client] Connection Successful!
2022-07-11 21:05:16 INFO (MainThread) [custom_components.crowipmodule] Established a connection with the Crow Ip Module
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Sent: b'STATUS \r\n'
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] ----------------------------------------
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Received: DA
DB
RO
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Parsing response line: DA
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Match found for DA
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] calling handler: handle_area_state_change for message: Area A Disarmed with data:
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Setting Area A Disarmed to True
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Invoking callback: callback_area_state_change
2022-07-11 21:05:16 DEBUG (MainThread) [custom_components.crowipmodule] The Crow Ip Module sent an area update event. Updating areas...
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] ----------------------------------------
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Parsing response line: DB
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Match found for DB
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] calling handler: handle_area_state_change for message: Area B Disarmed with data:
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Setting Area B Disarmed to True
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Invoking callback: callback_area_state_change
2022-07-11 21:05:16 DEBUG (MainThread) [custom_components.crowipmodule] The Crow Ip Module sent an area update event. Updating areas...
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] ----------------------------------------
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Parsing response line: RO
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Match found for RO
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] calling handler: handle_system_state_change for message: Ready On with data:
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Setting System State Ready On to True
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Invoking callback: callback_system_state_change
2022-07-11 21:05:16 DEBUG (MainThread) [custom_components.crowipmodule] Crow Ip Module sent a system update event. Updating system...
2022-07-11 21:05:16 DEBUG (MainThread) [pycrowipmodule.crow_base_client] ----------------------------------------
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.alarm_control_panel] Setting up alarm: A
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.alarm_control_panel] Setting up alarm: B
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX 
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.binary_sensor] Setting up zone: XXX
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] OrderedDict([(3, OrderedDict([('name', 'Modem')])), (4, OrderedDict([('name', 'Gatewayrouter')]))])
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Setting up output switch for system...
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Setting up output switch for system...
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Setting up relay switch for system...
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Setting up relay switch for system...
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Is_on=False
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Is_on=False
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Is_on=False
2022-07-11 21:05:17 DEBUG (MainThread) [custom_components.crowipmodule.switch] Is_on=False

and then we get... a reconnect!!

2022-07-11 21:08:39 ERROR (MainThread) [pycrowipmodule.crow_base_client] The server closed the connection. Reconnecting...
2022-07-11 21:08:39 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Disconnecting server...
2022-07-11 21:08:59 INFO (MainThread) [pycrowipmodule.crow_base_client] Starting connection to Crow IP Module... at XXX.xxx.XXX.xxx:5002
2022-07-11 21:08:59 INFO (MainThread) [pycrowipmodule.crow_base_client] Connection Successful!
2022-07-11 21:08:59 INFO (MainThread) [custom_components.crowipmodule] Established a connection with the Crow Ip Module
2022-07-11 21:08:59 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Sent: b'STATUS \r\n'
2022-07-11 21:08:59 DEBUG (MainThread) [pycrowipmodule.crow_base_client] ----------------------------------------
2022-07-11 21:08:59 DEBUG (MainThread) [pycrowipmodule.crow_base_client] Received: DA
DB
RO
...

**Comment by febalci** [comment]
Thanks for pointing out the problem @acdcnow. I will prepare a new version of pycrowipmodule on pypi and will inform you with the new version number. You are completely right, the "loop" parameter is removed in Python 3.10.
Planning to leave the "loop" parameter for the people who are not using 2022.7.x yet; like me...

**Comment by febalci** [comment]
v0.28 on the PyPi resolves this problem. In order to use 0.28, you should change the “pycrowipmodule==0.27” to “pycrowipmodule==0.28” in “manifest.json” file under “custom_components/crowipmodule” folder and restart HA
